package com.frc.investment.bean;

// Generated 2015-8-9 22:24:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Investment generated by hbm2java
 */
@Entity
@Table(name = "investment")
public class Investment implements java.io.Serializable {

	private Integer idAgTd;
	private String date;
	private double startPrice;
	private double stopPrice;
	private double minPrice;
	private double maxPrice;
	private Double volumeOfDeal;
	private Long amountOfDeal;
	private Long acountOfDeal;
	private String type;
	private String dataInterval;
	private String tradeTime;

	public Investment() {
	}

	public Investment(String date, double startPrice, double stopPrice,
			double minPrice, double maxPrice, String type) {
		this.date = date;
		this.startPrice = startPrice;
		this.stopPrice = stopPrice;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
		this.type = type;
	}

	public Investment(String date, double startPrice, double stopPrice,
			double minPrice, double maxPrice, Double volumeOfDeal,
			Long amountOfDeal, Long acountOfDeal, String type,
			String dataInterval, String tradeTime) {
		this.date = date;
		this.startPrice = startPrice;
		this.stopPrice = stopPrice;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
		this.volumeOfDeal = volumeOfDeal;
		this.amountOfDeal = amountOfDeal;
		this.acountOfDeal = acountOfDeal;
		this.type = type;
		this.dataInterval = dataInterval;
		this.tradeTime = tradeTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_ag_td", unique = true, nullable = false)
	public Integer getIdAgTd() {
		return this.idAgTd;
	}

	public void setIdAgTd(Integer idAgTd) {
		this.idAgTd = idAgTd;
	}

	@Column(name = "date", nullable = false, length = 12)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "startPrice", nullable = false, precision = 22, scale = 0)
	public double getStartPrice() {
		return this.startPrice;
	}

	public void setStartPrice(double startPrice) {
		this.startPrice = startPrice;
	}

	@Column(name = "stopPrice", nullable = false, precision = 22, scale = 0)
	public double getStopPrice() {
		return this.stopPrice;
	}

	public void setStopPrice(double stopPrice) {
		this.stopPrice = stopPrice;
	}

	@Column(name = "minPrice", nullable = false, precision = 22, scale = 0)
	public double getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(double minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "maxPrice", nullable = false, precision = 22, scale = 0)
	public double getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(double maxPrice) {
		this.maxPrice = maxPrice;
	}

	@Column(name = "volumeOfDeal", precision = 22, scale = 0)
	public Double getVolumeOfDeal() {
		return this.volumeOfDeal;
	}

	public void setVolumeOfDeal(Double volumeOfDeal) {
		this.volumeOfDeal = volumeOfDeal;
	}

	@Column(name = "amountOfDeal")
	public Long getAmountOfDeal() {
		return this.amountOfDeal;
	}

	public void setAmountOfDeal(Long amountOfDeal) {
		this.amountOfDeal = amountOfDeal;
	}

	@Column(name = "acountOfDeal")
	public Long getAcountOfDeal() {
		return this.acountOfDeal;
	}

	public void setAcountOfDeal(Long acountOfDeal) {
		this.acountOfDeal = acountOfDeal;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "dataInterval", length = 45)
	public String getDataInterval() {
		return this.dataInterval;
	}

	public void setDataInterval(String dataInterval) {
		this.dataInterval = dataInterval;
	}

	@Column(name = "tradeTime", length = 12)
	public String getTradeTime() {
		return this.tradeTime;
	}

	public void setTradeTime(String tradeTime) {
		this.tradeTime = tradeTime;
	}

}
